path: /kaggle/input/pee-dataset # dataset root dir
train: /kaggle/input/pee-dataset/images/train # train images (relative to 'path') 4 images
val: /kaggle/input/pee-dataset/images/valid # val images (relative to 'path') 4 images
test: /kaggle/input/pee-dataset/images/test # test images (optional)

# Classes
names:
  0: worker
  1: helmet
  2: vest
  3: gloves
  4: boots
  5: no_helmet
  6: no_vest
  7: no_gloves
  8: no_boots
